### PR TITLE
Add option to print test output

### PR DESCRIPTION
**Pull request by jimhester**
This allows use in GitHub Actions by setting
`option(rcmdcheck.test_output = TRUE)` in the workflow.

Fixes 121

### CODE REVIEW

**Comment by jimhester** [comment]
Not sure what the best way to test this would be. I guess create a new test fixture that doesn't have any failing tests?

**Comment by gaborcsardi** [comment]
So currently, if there are no failures then the whole testthat output is printed. If there are test failures, then only the failures are printed. Should be print the whole output, always, if the option is set?

**Comment by gaborcsardi** [comment]
@jimhester Also, when the check results are printed during the check (like on GHA?), then the print method is not used, so the test output will not be printed. I guess we would like to print the test output in this case as well? We could actually print the test output as it happens.

**Comment by jimhester** [comment]
The object does get printed in GHA, on check failures at https://github.com/r-lib/rcmdcheck/blob/22e242dbf1ee226915ab167e15580eeee1441d6f/R/package.R#L166-L167 and with auto-printing on success, as it is the last result. e.g. everything after 'R CMD check results' is coming from the print method (https://github.com/r-lib/rcmdcheck/runs/3556558380?check_suite_focus=true#step:11:82)

**Comment by jimhester** [comment]
I think the way it is would be fine, if there are failures having only the failure files being printed is probably what people would want, otherwise all of them.

**Comment by gaborcsardi** [comment]
In this case, let me just add the new option to the manual, and then I'll merge it.

**Comment by gaborcsardi** [comment]
Thanks!

**Pull request merged**
