### PR TITLE
Use brio::read_file()

### PR DESCRIPTION
**Pull request by hadley**
This gives a decent speed increase.

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I am afraid that it'll fail on Windows, no? But if this is really that slow, there should be another way to speed it up.

**Comment by hadley** [comment]
Why would it fail? I've left the existing line ending conversion intact.

**Comment by gaborcsardi** [comment]
Because brio forces UTF-8. Wasn't that the issue in roxygen2? I am not sure, but we'll see anyway.

**Comment by gaborcsardi** [comment]
The CI was failing already before, so that does not mean much. I'll take a look at it on Windows.

**Comment by hadley** [comment]
Anyway, I started on this because I though it might fix my invalid utf-8 character issue, but it only really delays the issue. So it's also fine to just close this.

**Comment by gaborcsardi** [comment]
I'll close this, because the check output is in the native encoding, so we cannot use brio here.

**Pull request closed without merging**
